### ISSUE TITLE
Flutter Doc Spelling

### ISSUE THREAD

**Issue by derekbking** [matthewfx/sleek_circular_slider#1]
shadowWidth is misspelled under the CustomSliderWidths parameters section.

**Comment by imSanjaySoni** [comment]
> shadowWidth is misspelled under the CustomSliderWidths parameters section.

I have corrected it. please wait for merge it with master branch.

**Comment by matthewfx** [comment]
@derekbking thanks!
@imSanjaySoni I just pushed some more changes for the README.md and among them fixed the spelling. I didn't notice your pull request. I'm sorry!

**Comment by imSanjaySoni** [comment]
No problem
