### ISSUE TITLE
assertion: line 45 pos 16: 'min <= max': is not true.

### ISSUE THREAD

**Issue by khashabawy** [matthewfx/sleek_circular_slider#15]
The following assertion was thrown building PlayOutPlayer(dirty, dependencies: [MediaQuery], state: _PlayOutPlayer#f3517):
'package:sleek_circular_slider/src/circular_slider.dart': Failed assertion: line 45 pos 16: 'min <= max': is not true.

**Comment by matthewfx** [comment]
It's because you must have passed a minimal value which is greater or equal to a maximum value. The generic Slider widget works in the exact same way.
