### ISSUE TITLE
Request: Animation Duration

### ISSUE THREAD

**Issue by ammarhemani** [matthewfx/sleek_circular_slider#19]
Functionality request: Animation Duration parameter when using the slider as a static progress bar instead of a slider. 

When I say animation duration, I mean being able to set the duration it takes for the progress bar to go from zero to the value set.

Side note: This is the best slider package out there for Flutter, and an enormous kudos to the authors!!

**Comment by matthewfx** [comment]
Currently, it calculates it dynamically based on the amount of change so it doesn't look awkward. I can think of a multiplier eventually :)

**Comment by matthewfx** [comment]
It has been added in v. 1.2
