### ISSUE TITLE
Error when initial value equals to min value

### ISSUE THREAD

**Issue by abdulmuaz97** [matthewfx/sleek_circular_slider#23]
### Problem!
This may seems strange but it actually gives an error when I set the **initial** value equals to the same **min** value.
I currently solved it by increase the initial value by 2.
Here's my code.
``` dart
@override
Widget build(BuildContext context) {
  return SleekCircularSlider(
    initialValue: widget.value <= widget.min ? widget.value + 2 : widget.value,
    innerWidget: _buildInnerWidget,
    appearance: CircularSliderAppearance(
      size: 200,
      customWidths: CustomSliderWidths(
        trackWidth: 2,
        progressBarWidth: 10,
      ),
      customColors: CustomSliderColors(
        progressBarColors: [
          const Color(0xffe74c3c),
          const Color(0xffe67e22),
          const Color(0xfff1c40f),
        ],
        trackColor: Colors.white12,
        shadowColor: const Color(0xffe74c3c),
      ),
      animationEnabled: true,
    ),
    min: widget.min,
    max: widget.max,
    onChange: (val) => setState(() => currentValue = val),
    onChangeEnd: (val) => widget.onChaged(val),
  );
}
```

### Error!
The error was in the framework since multiple things went wrong too inside the framework..

> The following assertion was thrown building Expanded(flex: 1):
> 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4224 pos 12: '!_dirty': is not true.
> 
> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
> In either case, please report this assertion by filing a bug on GitHub:
>   https://github.com/flutter/flutter/issues/new?template=BUG.md

Hope you can fix it as soon as possible.
Thanks.

**Comment by matthewfx** [comment]
Sorry but I'm very busy atm. I will try to do it but can't promise when

**Comment by matthewfx** [comment]
Hm - I can't replicate it. Closing it for now.
