### ISSUE TITLE
Circular gradient - show full gradient

### ISSUE THREAD

**Issue by MobileMon** [matthewfx/sleek_circular_slider#25]
How can I make the gradient be the full color spectrum even if the progress is only partial? For instance, if the progress is only 0.2, I actually want to see the whole sweep from blue to red. Not just the blue part 

Another flutter widget has this same issue:
https://github.com/diegoveloper/flutter_percent_indicator/issues/31

any clue how to solve this?

**Comment by matthewfx** [comment]
I will think of it when I finally find time to work on it again :)

**Comment by MobileMon** [comment]
Thanks.

I actually found another open source widget to accomplish this. I think it will help you

Check it out

https://github.com/ShaunRain/gradient-progress

**Comment by matthewfx** [comment]
It has been added in v. 1.2
