### ISSUE TITLE
(Initial) Value greater than Max Value

### ISSUE THREAD

**Issue by ciprian-stoian** [matthewfx/sleek_circular_slider#3]
First of all, great work on this lib! I love how beautiful and customizable it is!

I ran into a scenario where the `initialvalue` field was updated with a value greater than the `max`.
Imagine if someone set a number of calories, but managed to pass that number. It would be nice if we could represent that, maybe with a separated slider color as well to represent that the `max` value was overpassed.

Keep up the great work!

**Comment by ciprian-stoian** [comment]
I have found a workaround for this with an `innerWidget` of the same size which overlaps the parent widget. This can be closed if you consider the workaround is enough and the extra implementation doesn't provide much value. But maybe such an example should be valuable to showcase on the main page.

**Comment by matthewfx** [comment]
Hi Ciprian, I wouldn't call it an issue but a feature request. I think it might be confusing after all if one uses the generic slider widget it has the same behaviour (a value can't be greater than a max value). On the other hand, I understand it would be a nice feature in some cases and I might consider adding it in the future.  Thanks for your comments! Good luck with your an app your working on!
