### ISSUE TITLE
Ability to show innerWidget in spinnerMode.

### ISSUE THREAD

**Issue by mekery** [matthewfx/sleek_circular_slider#39]
Awesome widget!

innerWidget not shown in spinnerMode by default, is there any possible to show innerWidget when spinnerMode set true, cause I want to show some tips inside where use as spinner.

Thanks in advance.

**Comment by matthewfx** [comment]
Hi, 

Thanks, man. Re the inner widget and the spinner mode, the short answer is no. The whole widget is animated atm which means the inner widget would be rotating too. I might think about changing the current implementation but to tell you the truth I'm busy and not sure if or when I will be able to do it. The easiest way for you to have something inside the spinner would be to use the Stack widget to add some other widget on top of the spinner. I hope it helps.

Cheers,

mat
