### ISSUE TITLE
set currently value of slider

### ISSUE THREAD

**Issue by mohammadne** [matthewfx/sleek_circular_slider#4]
in my case I have a music player and I need the currently value of slider , update based on the music position .
I want `value` parameter like default flutter slider.

**Comment by ArthurDevv** [comment]
The `initialValue` parameter did the job for me. The author could rename that parameter to make it less confusing.

**Comment by matthewfx** [comment]
yeah, the `initialValue` is the parameter you're looking for. The name might be confusing and I will consider changing it when I release an update.
