### ISSUE TITLE
Disabling Sliding Property

### ISSUE THREAD

**Issue by Chetan-Goyal** [matthewfx/sleek_circular_slider#41]
I have used a button widget inside `SleekCircularSlider()` but when button is disabled, I want to disable the slide property of the slider and vice versa .
In other words, I want to do **enable/ disable slider based on a boolean value**.

I was wondering if is there any way to make this thing possible as I was unable to find any parameter that would be helpful in my case.

**Comment by Chetan-Goyal** [comment]
Issue is fixed by passing `null` to `onChanged` of `SleekCircularSlider()`.

**Comment by matthewfx** [comment]
Awesome! 👍
