### ISSUE TITLE
After setting initial value ,min and max dynamically the slider doesnt reset to intitial value .

### ISSUE THREAD

**Issue by Aashutosh3804** [matthewfx/sleek_circular_slider#51]
After setting initial value ,min and max dynamically the slider doesnt reset to intitial value .It show same position of slider ,though min, max change are working

**Comment by matthewfx** [comment]
Hey - the initial value is a misleading name... I should have called it simply a value. In order to reset it to an initial value you need to do it in your code. Sorry...
