### ISSUE TITLE
Custom handle

### ISSUE THREAD

**Issue by spacekestrel** [matthewfx/sleek_circular_slider#60]
Is there a way to make custom handler, like icon widget or canvas?

**Comment by matthewfx** [comment]
No, currently there isn't.

**Comment by spacekestrel** [comment]
That sucksОтправлено с устройства Galaxy
-------- Исходное сообщение --------От: Mat Nuckowski ***@***.***> Дата: 22.07.2021  09:22  (GMT+03:00) Кому: matthewfx/sleek_circular_slider ***@***.***> Копия: spacekestrel ***@***.***>, Author ***@***.***> Тема: Re: [matthewfx/sleek_circular_slider] Custom handle (#60) 
No, currently there isn't.

**Comment by matthewfx** [comment]
@spacekestrel  If the only think you can say is "that sucks" I'd suggest you should write your own better slider. No one has paid me for my work on this widget and people like you make me think twice before I decide to share any code ever again. People like you are the reason many engineers inclined to do open source libraries change their minds after stumbling upon comments like yours...

**Comment by spacekestrel** [comment]
Mate, if you had a rough day - it's not my problem. To make the handle
customizable is not that hard. It is actually pretty easy to do and instead
of whining you could just strain your ass and do it.
And, if you don't like criticism - just delete your packages. My god, what
a snowflake...

**Comment by matthewfx** [comment]
Strain your ass and do it if that's so easy then. I don't see any repos you have done by yourself though... What a pathetic person you must be...
