### ISSUE TITLE
Can I change the dot to an icon?

### ISSUE THREAD

**Issue by mariapapag95** [matthewfx/sleek_circular_slider#61]
Hi, this is a great package. Thanks for making it!

I see that you can change the dot color, but I would like to change it from a dot to an icon. How should I do that?

<img width="481" alt="Screen Shot 2021-08-12 at 1 33 01 PM" src="https://user-images.githubusercontent.com/47039896/129242378-a5e31961-1999-4fd9-b2f2-5d64fa5daa75.png">
<img width="252" alt="Screen Shot 2021-08-12 at 1 32 13 PM" src="https://user-images.githubusercontent.com/47039896/129242379-a2fd369a-d6ef-42a9-9ef2-ac58e3547b36.png">

**Comment by matthewfx** [comment]
Hi Maria, I'm sorry but that is currently not possible. It is on my to-do list but I'm very busy atm and don't know when I will be able to look at it. If you can't wait you can fork it and implement that by yourself. Have a nice day!
