### ISSUE TITLE
Has this been abandoned? Anyone have a replacement? 🤔

### ISSUE THREAD

**Issue by cliftonlabrum** [matthewfx/sleek_circular_slider#89]
This repo hasn't had an update in quite a while--which is a shame because this is one of the nicest widgets I've found. 💯

Has anyone found or created an alternative that's getting updates? 

Several of the open issues on this are features I'd love to see. I'm a little too new to Flutter to contribute myself. 😅

**Comment by SamMakesThings** [comment]
Also listening here

**Comment by matthewfx** [comment]
I'm very busy with my work but might add some fixes at the end of January. I doubt I will be adding any new features though.
