### ISSUE TITLE
how to change slider value without user interaction

### ISSUE THREAD

**Issue by yase-hesham** [matthewfx/sleek_circular_slider#9]
Hello 
I was searching for a circle slider and i found yours , thanks for it ^^
so i'm using it for playing an audio , and i need to change it's value depends on my audio position, is there any way to handle this ?

**Comment by matthewfx** [comment]
Hi, Please check the random_value_page.dart in the example folder. Basically you need to pass that value to the `initialValue` parameter and refresh the state and don't pass anything into `onChange` or `onChangeEnd`and that will disable user interaction.
